enum AchievementType {
    LESSON_CLEAN_CODE = 'LESSON_CLEAN_CODE',
    LESSON_DESIGN_PATTERN = 'LESSON_DESIGN_PATTERN',
    CHALLENGE_CLEAN_CODE_LVL_1 = 'CHALLENGE_CLEAN_CODE_LVL_1',
    CHALLENGE_CLEAN_CODE_LVL_2 = 'CHALLENGE_CLEAN_CODE_LVL_2',
    CHALLENGE_CLEAN_CODE_LVL_3 = 'CHALLENGE_CLEAN_CODE_LVL_3',
    CHALLENGE_DESIGN_PATTERN_LVL_1 = 'CHALLENGE_DESIGN_PATTERN_LVL_1',
    CHALLENGE_DESIGN_PATTERN_LVL_2 = 'CHALLENGE_DESIGN_PATTERN_LVL_2',
    CHALLENGE_DESIGN_PATTERN_LVL_3 = 'CHALLENGE_DESIGN_PATTERN_LVL_3',
    GAMES_COMPLETED_10 = 'GAMES_COMPLETED_10',
    GAMES_COMPLETED_50 = 'GAMES_COMPLETED_50',
    GAMES_COMPLETED_100 = 'GAMES_COMPLETED_100',
}