export enum SubjectType {
    CLEAN_CODE = 'CLEAN_CODE',
    DESIGN_PATTERN = 'DESIGN_PATTERN',
}

export enum LessonType {
    VIDEO = 'VIDEO',
    WRITTEN = 'WRITTEN',
}

export enum AchievementType {
    LESSON_CLEAN_CODE = 'LESSON_CLEAN_CODE',
    LESSON_DESIGN_PATTERN = 'LESSON_DESIGN_PATTERN',
    CHALLENGE_CLEAN_CODE_LVL_1 = 'CHALLENGE_CLEAN_CODE_LVL_1',
    CHALLENGE_CLEAN_CODE_LVL_2 = 'CHALLENGE_CLEAN_CODE_LVL_2',
    CHALLENGE_CLEAN_CODE_LVL_3 = 'CHALLENGE_CLEAN_CODE_LVL_3',
    CHALLENGE_DESIGN_PATTERN_LVL_1 = 'CHALLENGE_DESIGN_PATTERN_LVL_1',
    CHALLENGE_DESIGN_PATTERN_LVL_2 = 'CHALLENGE_DESIGN_PATTERN_LVL_2',
    CHALLENGE_DESIGN_PATTERN_LVL_3 = 'CHALLENGE_DESIGN_PATTERN_LVL_3',
}

export enum Level {
    LEVEL_1 = 'LEVEL_1',
    LEVEL_2 = 'LEVEL_2',
    LEVEL_3 = 'LEVEL_3',
}

export enum QuestionType {
    GAP_GAME = 'GAP_GAME',
    QUIZ = 'QUIZ',
}
